// Automatically generated by Interoptopus.

#pragma warning disable 0105
using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Cognite.Kuiper;
#pragma warning restore 0105

namespace Cognite.Kuiper
{
    public static partial class Interop
    {
        public const string NativeLib = "kuiper_net";

        static Interop()
        {
        }


        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "compile_expression")]
        public static extern CompileResult compile_expression(string data, SliceInputStringWrapper inputs);

        public static CompileResult compile_expression(string data, IntPtr[] inputs)
        {
            var inputs_pinned = GCHandle.Alloc(inputs, GCHandleType.Pinned);
            var inputs_slice = new SliceInputStringWrapper(inputs_pinned, (ulong) inputs.Length);
            try
            {
                return compile_expression(data, inputs_slice);;
            }
            finally
            {
                inputs_pinned.Free();
            }
        }

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_destroy")]
        public static extern KuiperFFIError kuiper_expression_destroy(ref IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        public static void kuiper_expression_destroy_checked(ref IntPtr context)
        {
            var rval = kuiper_expression_destroy(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_new")]
        public static extern KuiperFFIError kuiper_expression_new(ref IntPtr context);

        public static void kuiper_expression_new_checked(ref IntPtr context)
        {
            var rval = kuiper_expression_new(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_execute")]
        public static extern ExecuteResult kuiper_expression_execute(IntPtr context, SliceInputStringWrapper data);

        public static ExecuteResult kuiper_expression_execute(IntPtr context, IntPtr[] data)
        {
            var data_pinned = GCHandle.Alloc(data, GCHandleType.Pinned);
            var data_slice = new SliceInputStringWrapper(data_pinned, (ulong) data.Length);
            try
            {
                return kuiper_expression_execute(context, data_slice);;
            }
            finally
            {
                data_pinned.Free();
            }
        }

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_result_destroy")]
        public static extern KuiperFFIError kuiper_expression_result_destroy(ref IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        public static void kuiper_expression_result_destroy_checked(ref IntPtr context)
        {
            var rval = kuiper_expression_result_destroy(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_result_new")]
        public static extern KuiperFFIError kuiper_expression_result_new(ref IntPtr context);

        public static void kuiper_expression_result_new_checked(ref IntPtr context)
        {
            var rval = kuiper_expression_result_new(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_expression_result_data")]
        public static extern IntPtr kuiper_expression_result_data(IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_error_destroy")]
        public static extern KuiperFFIError kuiper_error_destroy(ref IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        public static void kuiper_error_destroy_checked(ref IntPtr context)
        {
            var rval = kuiper_error_destroy(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_error_new")]
        public static extern KuiperFFIError kuiper_error_new(ref IntPtr context);

        public static void kuiper_error_new_checked(ref IntPtr context)
        {
            var rval = kuiper_error_new(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_error_error")]
        public static extern IntPtr kuiper_error_error(IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_input_string_wrapper_destroy")]
        public static extern KuiperFFIError kuiper_input_string_wrapper_destroy(ref IntPtr context);

        /// Destroys the given instance.
        ///
        /// # Safety
        ///
        /// The passed parameter MUST have been created with the corresponding init function;
        /// passing any other value results in undefined behavior.
        public static void kuiper_input_string_wrapper_destroy_checked(ref IntPtr context)
        {
            var rval = kuiper_input_string_wrapper_destroy(ref context);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        [DllImport(NativeLib, CallingConvention = CallingConvention.Cdecl, EntryPoint = "kuiper_input_string_wrapper_new")]
        public static extern KuiperFFIError kuiper_input_string_wrapper_new(ref IntPtr context, string data);

        public static void kuiper_input_string_wrapper_new_checked(ref IntPtr context, string data)
        {
            var rval = kuiper_input_string_wrapper_new(ref context, data);;
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct CompileResult
    {
        public OptionKuiperError error;
        public OptionKuiperExpression result;
    }

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct ExecuteResult
    {
        public OptionKuiperError error;
        public OptionKuiperExpressionResult result;
    }

    public enum KuiperFFIError
    {
        SUCCESS = 1,
        NULL = 2,
        PANIC = 3,
    }

    ///A pointer to an array of data someone else owns which may not be modified.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct SliceInputStringWrapper
    {
        ///Pointer to start of immutable data.
        IntPtr data;
        ///Number of elements.
        ulong len;
    }

    public partial struct SliceInputStringWrapper : IEnumerable<IntPtr>
    {
        public SliceInputStringWrapper(GCHandle handle, ulong count)
        {
            this.data = handle.AddrOfPinnedObject();
            this.len = count;
            Console.WriteLine("Create slice wrapper: {0:X}, {1}", data, len);
        }
        public SliceInputStringWrapper(IntPtr handle, ulong count)
        {
            this.data = handle;
            this.len = count;
        }
        public IntPtr this[int i]
        {
            get
            {
                if (i >= Count) throw new IndexOutOfRangeException();
                var size = Marshal.SizeOf(typeof(IntPtr));
                var ptr = new IntPtr(data.ToInt64() + i * size);
                return Marshal.PtrToStructure<IntPtr>(ptr);
            }
        }
        public IntPtr[] Copied
        {
            get
            {
                var rval = new IntPtr[len];
                for (var i = 0; i < (int) len; i++) {
                    rval[i] = this[i];
                }
                return rval;
            }
        }
        public int Count => (int) len;
        public IEnumerator<IntPtr> GetEnumerator()
        {
            for (var i = 0; i < (int)len; ++i)
            {
                yield return this[i];
            }
        }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }


    ///Option type containing boolean flag and maybe valid data.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct OptionKuiperError
    {
        ///Element that is maybe valid.
        IntPtr t;
        ///Byte where `1` means element `t` is valid.
        byte is_some;
    }

    public partial struct OptionKuiperError
    {
        public static OptionKuiperError FromNullable(IntPtr? nullable)
        {
            var result = new OptionKuiperError();
            if (nullable.HasValue)
            {
                result.is_some = 1;
                result.t = nullable.Value;
            }

            return result;
        }

        public IntPtr? ToNullable()
        {
            return this.is_some == 1 ? this.t : (IntPtr?)null;
        }
    }


    ///Option type containing boolean flag and maybe valid data.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct OptionKuiperExpression
    {
        ///Element that is maybe valid.
        IntPtr t;
        ///Byte where `1` means element `t` is valid.
        byte is_some;
    }

    public partial struct OptionKuiperExpression
    {
        public static OptionKuiperExpression FromNullable(IntPtr? nullable)
        {
            var result = new OptionKuiperExpression();
            if (nullable.HasValue)
            {
                result.is_some = 1;
                result.t = nullable.Value;
            }

            return result;
        }

        public IntPtr? ToNullable()
        {
            return this.is_some == 1 ? this.t : (IntPtr?)null;
        }
    }


    ///Option type containing boolean flag and maybe valid data.
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public partial struct OptionKuiperExpressionResult
    {
        ///Element that is maybe valid.
        IntPtr t;
        ///Byte where `1` means element `t` is valid.
        byte is_some;
    }

    public partial struct OptionKuiperExpressionResult
    {
        public static OptionKuiperExpressionResult FromNullable(IntPtr? nullable)
        {
            var result = new OptionKuiperExpressionResult();
            if (nullable.HasValue)
            {
                result.is_some = 1;
                result.t = nullable.Value;
            }

            return result;
        }

        public IntPtr? ToNullable()
        {
            return this.is_some == 1 ? this.t : (IntPtr?)null;
        }
    }



    public partial class KuiperExpression : IDisposable
    {
        private IntPtr _context;

        private KuiperExpression() {}

        public static KuiperExpression New()
        {
            var self = new KuiperExpression();
            var rval = Interop.kuiper_expression_new(ref self._context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
            return self;
        }

        public void Dispose()
        {
            var rval = Interop.kuiper_expression_destroy(ref _context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        public ExecuteResult Execute(SliceInputStringWrapper data)
        {
            return Interop.kuiper_expression_execute(_context, data);
        }

        public ExecuteResult Execute(IntPtr[] data)
        {
            return Interop.kuiper_expression_execute(_context, data);
        }

        public IntPtr Context => _context;
    }


    public partial class KuiperExpressionResult : IDisposable
    {
        private IntPtr _context;

        private KuiperExpressionResult() {}

        public static KuiperExpressionResult New()
        {
            var self = new KuiperExpressionResult();
            var rval = Interop.kuiper_expression_result_new(ref self._context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
            return self;
        }

        public void Dispose()
        {
            var rval = Interop.kuiper_expression_result_destroy(ref _context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        public string Data()
        {
            var s = Interop.kuiper_expression_result_data(_context);
            return Marshal.PtrToStringAnsi(s);
        }

        public IntPtr Context => _context;
    }


    public partial class KuiperError : IDisposable
    {
        private IntPtr _context;

        private KuiperError() {}

        public static KuiperError New()
        {
            var self = new KuiperError();
            var rval = Interop.kuiper_error_new(ref self._context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
            return self;
        }

        public void Dispose()
        {
            var rval = Interop.kuiper_error_destroy(ref _context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        public string Error()
        {
            var s = Interop.kuiper_error_error(_context);
            return Marshal.PtrToStringAnsi(s);
        }

        public IntPtr Context => _context;
    }


    public partial class InputStringWrapper : IDisposable
    {
        private IntPtr _context;

        private InputStringWrapper() {}

        public static InputStringWrapper New(string data)
        {
            var self = new InputStringWrapper();
            var rval = Interop.kuiper_input_string_wrapper_new(ref self._context, data);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
            return self;
        }

        public void Dispose()
        {
            var rval = Interop.kuiper_input_string_wrapper_destroy(ref _context);
            if (rval != KuiperFFIError.SUCCESS)
            {
                throw new InteropException<KuiperFFIError>(rval);
            }
        }

        public IntPtr Context => _context;
    }



    public class InteropException<T> : Exception
    {
        public T Error { get; private set; }

        public InteropException(T error): base($"Something went wrong: {error}")
        {
            Error = error;
        }
    }

}
