class KuiperError(BaseException): ...
class KuiperCompileError(KuiperError): ...
class KuiperRuntimeError(KuiperError): ...

class KuiperExpression(object):
    def run(self, input: str) -> str: ...

def compile_expression(expression: str, inputs: list[str]) -> KuiperExpression: ...
