// This file is automatically created by kuiper_documentation/codegen.py. Do not edit it directly.
//
// To change the content of this file, edit kuiper_documentation/functions.yaml instead.

export type KuiperInput = {
    label: string,
    description: string,
};

export const builtIns: KuiperInput[] = [
    { label: "acos", description: "`acos(x)`: Return the inverse cosine of `x` in radians between 0 and pi." },
    { label: "all", description: "`all(x)`: Return `true` if all items in the array `x` is true." },
    { label: "any", description: "`any(x)`: Return `true` if any items in the array `x` is true." },
    { label: "asin", description: "`asin(x)`: Return the inverse sine of `x` in radians between -pi/2 and pi/2." },
    { label: "atan", description: "`atan(x)`: Return the inverse tangent of `x` in radians between -pi/2 and pi/2." },
    { label: "atan2", description: "`atan2(x, y)`: Return the inverse tangent of `x`/`y` in radians between -pi and pi." },
    { label: "case", description: "`case(x, c1, r1, c2, r2, ..., (default))`: Compare `x` to each of `c1`, `c2`, etc. and return the matching `r1`, `r2` of the first match. If no entry matches, a final optional expression can be returned as default." },
    { label: "ceil", description: "`ceil(x)`: Return `x` rounded up to the nearest integer." },
    { label: "chars", description: "`chars(x)`: Create an array of characters from a string." },
    { label: "chunk", description: "`chunk(x, s)`: Convert the list `x` into several lists of length at most `s`" },
    { label: "coalesce", description: "`coalesce(a, b, ...)`: Return the first non-null value in the list of values." },
    { label: "concat", description: "`concat(x, y, ...)`: Concatenate any number of strings." },
    { label: "contains", description: "`contains(x, a)`: Return `true` if the array or string `x` contains item `a`." },
    { label: "cos", description: "`cos(x)`: Return the cosine of `x`, where `x` is in radians." },
    { label: "digest", description: "`digest(a, b, ...)`: Compute the SHA256 hash of the list of values." },
    { label: "distinct_by", description: "`distinct_by(x, (a(, b)) => ...)`: Return a list or object where the elements are distinct by the returned value of the given lambda function. The lambda function either takes list values, or object (value, key) pairs." },
    { label: "ends_with", description: "`ends_with(item, substring)`: Return `true` if `item` ends with `substring`." },
    { label: "except", description: "`except(x, (v(, k)) => ...)` or `except(x, l)`: Return a list or object where keys or entries maching the predicate have been removed." },
    { label: "exp", description: "`exp(x)`: Return e to the power of `x`." },
    { label: "filter", description: "`filter(x, it => ...)`: Remove any item from the list `x` where the lambda function returns `false` or `null`." },
    { label: "flatmap", description: "`flatmap(x, it => ...)`: Apply the lambda function to every item in the list `x` and flattens the result." },
    { label: "float", description: "`float(x)`: Convert `x` into a floating point number if possible. If the conversion fails, the whole mapping will fail." },
    { label: "floor", description: "`floor(x)`: Return `x` rounded down to the nearest integer." },
    { label: "format_timestamp", description: "`format_timestamp(x, f)`: Convert the Unix timestamp `x` into a string representation based on the format `f`." },
    { label: "if", description: "`if(x, y, (z))`: Return `y` if `x` evaluates to `true`, otherwise return `z`, or `null` if `z` is omitted." },
    { label: "if_value", description: "`if_value(item, item => ...)`: Map a value using a lambda if the value is not null. This is useful if you need to combine parts of some complex object or result of a longer calculation." },
    { label: "int", description: "`int(x)`: Convert `x` into an integer if possible. If the conversion fails, the whole mapping will fail." },
    { label: "join", description: "`join(a, b, ...)`: Return the union of the given objects or arrays. If a key is present in multiple objects, each instance of the key is overwritten by later objects. Arrays are simply merged." },
    { label: "length", description: "`length(x)`: Return the length on the list, string or object `x`." },
    { label: "log", description: "`log(x, y)`: Return the base `y` logarithm of `x`." },
    { label: "lower", description: "`lower(x)`: Convert all characters in the string `x` to lowercase. If `x` is a boolean or number, it will be converted to a string." },
    { label: "map", description: "`map(x, (it(, index)) => ...)`: Apply the lambda function to every item in the list `x`. The lambda takes an optional second input which is the index of the item in the list." },
    { label: "max", description: "`max(a, b, ...)`: Returns the larger of the given numbers. Can also be used on an array." },
    { label: "min", description: "`min(a, b, ...)`: Returns the smaller of the given numbers. Can also be used on an array." },
    { label: "now", description: "`now()`: Return the current time as a millisecond Unix timestamp, that is, the number of milliseconds since midnight 1/1/1970 UTC." },
    { label: "pairs", description: "`pairs(x)`: Convert the object `x` into a list of key/value pairs." },
    { label: "parse_json", description: "`parse_json(string)`: Parse a string as a JSON object, which can be used in further transformations. If the passed value isn't a string, it's returned as-is." },
    { label: "pow", description: "`pow(x, y)`: Return `x` to the power of `y`" },
    { label: "reduce", description: "`reduce(x, (acc, val) => ..., init)`: Return the value obtained by reducing the list `x`. The lambda function is called once for each element in the list `val`, and the returned value is passed as `acc` in the next iteration. The `init` will be given as the initial `acc` for the first call to the lambda function." },
    { label: "regex_all_captures", description: "`regex_all_captures(haystack, regex)`: Return an array of objects containing all capture groups from each match of the regex in the haystack. Unnamed capture groups are named after their index, so the match itself is always included as capture group `0`. If no match is found, this returns an empty array." },
    { label: "regex_all_matches", description: "`regex_all_matches(haystack, regex)`: Return an array of all the substrings that match the regex. If no match is found, this returns an empty array. If you only need the first match, use [regex_first_match](#regex_first_match)." },
    { label: "regex_first_captures", description: "`regex_first_captures(haystack, regex)`: Return an object containing all capture groups from the first match of the regex in the haystack. Unnamed capture groups are named after their index, so the match itself is always included as capture group `0`. If no match is found, this returns null." },
    { label: "regex_first_match", description: "`regex_first_match(haystack, regex)`: Return the first substring in the haystack that matches the regex. If no match is found, this returns `null`. Prefer [regex_is_match](#regex_is_match) if all you need is to check for the existence of a match." },
    { label: "regex_is_match", description: "`regex_is_match(haystack, regex)`: Return `true` if the haystack matches the regex. Prefer this over the other regex methods if you only need to check for the presence of a match." },
    { label: "regex_replace", description: "`regex_replace(haystack, regex, replace)`: Replace the first occurrence of the regex in the haystack. The replace object supports referencing capture groups using either the index (`$1`) or the name (`$group`). Use `$$` if you need a literal `$` symbol. `${group}` is equivalent to `$group` but lets you specify the group name exactly." },
    { label: "regex_replace_all", description: "`regex_replace_all(haystack, regex, replace)`: Replace each occurrence of the regex in the haystack. See [regex_replace](#regex_replace) for details." },
    { label: "replace", description: "`replace(a, b, c)`: Replaces a string with another string" },
    { label: "round", description: "`round(x)`: Return `x` rounded to the nearest integer." },
    { label: "select", description: "`select(x, (v(, k)) => ...)` or `select(x, [1, 2, 3])`: Return a list or object where the lambda returns true. If the second argument is a list, the list values or object keys found in that list are used to select from the source." },
    { label: "sin", description: "`sin(x)`: Return the sine of `x`, where `x` is in radians." },
    { label: "slice", description: "`slice(x, start(, end))`: Create a sub-array from an array `x` from `start` to `end`. If `end is not specified, go from `start` the end of the array. If `start` or `end` are negative, count from the end of the array." },
    { label: "split", description: "`split(a, b)`: Split string `a` on any occurences of `b`. If `b` is an empty string, this will split on each character, including before the first and after the last." },
    { label: "sqrt", description: "`sqrt(x)`: Return the square root of `x`." },
    { label: "starts_with", description: "`starts_with(item, substring)`: Return `true` if `item` starts with `substring`." },
    { label: "string", description: "`string(x)`: Convert `x` into a string." },
    { label: "string_join", description: "`string_join(x(, a))`: Return a string with all the elements of `x`, separated by `a`. If `a` is omitted, the strings will be joined without any separator." },
    { label: "substring", description: "`substring(x, start(, end))`: Create a substring of an input string `x` from `start` to `end`. If `end` is not specified, go from `start` to end of string. If `start` or `end` are negative, count from the end of the string." },
    { label: "sum", description: "`sum(x)`: Sum the numbers in the array `x`." },
    { label: "tail", description: "`tail(x(, n))`: Take the last element of the list `x`. If `n` is given, takes the last `n` elements, and returns a list if `n` > 1." },
    { label: "tan", description: "`tan(x)`: Return the tangent of `x`, where `x` is in radians." },
    { label: "to_object", description: "`to_object(x, val => ...(, val => ...))`: Convert the array `x` into an object by producing the key and value from two lambdas." },
    { label: "to_unix_timestamp", description: "`to_unix_timestamp(x, f)`: Convert the string `x` into a millisecond Unix timestamp using the format string `f`." },
    { label: "translate", description: "`translate(x, from, to)`: Replace characters in the string `x` found in the string `from` with the corresponding character in the string `to`. If `to` and `from` are of different lengths, the expression will fail." },
    { label: "trim_whitespace", description: "`trim_whitespace(x)`: Remove any whitespace from the start and end of `x`" },
    { label: "try_bool", description: "`try_bool(a, b)`: Try convert `a` to a boolean, if it fails, return `b`." },
    { label: "try_float", description: "`try_float(a, b)`: Try convert `a` to a float, if it fails, return `b`." },
    { label: "try_int", description: "`try_int(a, b)`: Try convert `a` to a int, if it fails, return `b`." },
    { label: "upper", description: "`upper(x)`: Convert all characters in the string `x` to uppercase. If `x` is a boolean or number, it will be converted to a string first." },
    { label: "zip", description: "`zip(x, y, ..., (i1, i2, ...) => ...)`: Take a number of arrays, call the given lambda function on each entry, and return a single array from the result of each call. The returned array will be as long as the longest argument, null will be given for the shorter input arrays when they run out." },
];
